### ISSUE TITLE
SPARK GNAT BUG DETECTED (spark) GCC error.

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#14]
Hello,
I've the following issue while executing SPARK installed with gnat-builder makefile:
```
% gnatprove -P automate.gpr src/insrc.ads
Phase 1 of 2: generation of Global contracts ...
Phase 2 of 2: flow analysis and proof ...
+===========================GNAT BUG DETECTED==============================+
| T? (spark) GCC error:                                                 |
| could not add file /opt/Automate/obj/g   |
|    natprove/insrc__idauto__balance.mlw to the session:
File "/opt/Automate/obj/gnatprove/insrc__idauto__balance.mlw", line 3, characters 1-38:
Library file not found: _gnatprove_standard                                |
```
After discussion on SPARK list, it comes that why3 is installed in ${prefix} from gnat-builder makefile instead of spark2014-build/install/libexec/spark from prefix in why3 makefile.
The declared prefix in gnat-builder makefile make puzzle the one in why3 makefile.
As a workaround, I comment out the prefix declaration in gnat-builder makefile.
It's then ok:
```
% gnatprove -P automate.gpr src/insrc.ads
Phase 1 of 2: generation of Global contracts ...
Phase 2 of 2: flow analysis and proof ...
...
Summary logged in /opt/Automate/obj/gnatprove/gnatprove.out
```
HTH, Pascal.

**Comment by steve-cs** [comment]
That's a good clue.  I knew something was broken somewhere, but never got around to finding/fixing it properly.  This is something I'd like to fix.  Could you provide a pointer/link to the discussion?

**Comment by steve-cs** [comment]
@Blady-Com : I'm hoping that commit https://github.com/steve-cs/gnat-builder/commit/01ccb972a856454ac224b3459648293eeb255598 fixes this issue.  It should provide the same local effect when building spark2014/why3 as you did by commenting out the definition of prefix globally.  It does seem to populate spark2014-build/install/libexec/spark when before it didn't.

Please confirm.  Thanks.

**Comment by Blady-Com** [comment]
Hello Steve,
The unset doesn't work with my make version (GNU Make 3.81):
`	unset prefix && echo pref2 $(prefix)`
gives:
`pref2 /usr/local`
I've found some ways suitable for makefile:
https://www.gnu.org/software/make/manual/html_node/Undefine-Directive.html
Unfortunately it doesn't work with my make version.

Moreover, prefix is not used by "all" target in SPARK makefile nor "install-all" target as it installs stuff in predefined install folder.
prefix is used by the command:
`cp -a spark2014-build/install/* $(prefix)`
I propose simply to set a dedicated prefix name as:
`cp -a spark2014-build/install/* $(spark_prefix)`

What do think about?
HTH, Pascal.

**Comment by steve-cs** [comment]
There is confusion here.  Make is working as expected.  The "unset prefix" removes the definition of prefix in the environment of the enclosed "make -C spark2014-build".

Your "echo pref2 $(prefix)" already has $(prefix) replaced before echo is even called, so this tests nothing.  Please put echo pref2 $(prefix) inside a test shell script or an enclosed makefile to see your mistake.

The Undefined directive is also unsuitable because that undefines prefix in the gnat-builder makefile which I don't want to do.  If I wanted to go that route I could just rename all instances of prefix to gnat_prefix.  But I don't want to do that either as eliminating the collision just within the spark2014 build seems much simpler and more direct.

I strongly suspect that if my definition was causing a problem, it is within the why3 configure which is called by the spark2014 makefile.

Creating a spark_prefix variable won't help any problem caused by the existence of a prefix variable.  This can't be the right approach.

> What do think about?

I think you have a different or additional problem.  If you are still having an issue, I need more info in order to understand or replicate it.

**Comment by Blady-Com** [comment]
Hello Steve,
The gnat2why configure seems to give the correct prefix in generated makefile,
/opt/src-2020/spark2014-build/gnat2why/Makefile:
```
...
prefix	    = /opt/src-2020/spark2014-build/install/libexec/spark
...
```

I tried with a dummy makefile:
```
% cat dummy.mk 
all:
	echo pref_dum $(prefix)
```

I made these changes:
```
.PHONY: spark2014-install
spark2014-install:
#	make -C spark2014-build install-all
#	$(sudo) cp -a spark2014-build/install/* $(prefix)
	echo pref1 $(prefix)
	unset prefix && make -f dummy.mk
	make -f dummy.mk
```

The internal declared prefix is not transfered:
```
% make spark2014-install            
echo pref1 /usr/local
pref1 /usr/local
unset prefix && make -f dummy.mk
echo pref_dum 
pref_dum
make -f dummy.mk
echo pref_dum 
pref_dum
```
But the external defined prefix is transfered whatever unset used or not:
```
% make spark2014-install prefix=/opt
echo pref1 /opt
pref1 /opt
unset prefix && make -f dummy.mk
echo pref_dum /opt
pref_dum /opt
make -f dummy.mk
echo pref_dum /opt
pref_dum /opt
```
Best, Pascal.

**Comment by steve-cs** [comment]
Interesting, good catch.  I didn't expect that and don't understand yet why there's a difference.  Perhaps explicitly setting prefix to nothing (instead of unset) yields a more predictable result without upsetting configure/make of why3.  I'm guessing that explicitly passing prefix as an empty make definition is cleaner than hacking an environment variable (which failed as you've shown).  I'll give it some more thought after I get some sleep.

**Comment by steve-cs** [comment]
Found it.  Command line definitions are included in MAKEFLAGS as well for recursive make.  This confuses the spark/why3 build in a near identical way. Simplest workaround would seem to be use gnat-prefix instead of prefix.

`make spark2014 spark2014-install gnat-prefix=/usr/local`

Commit https://github.com/steve-cs/gnat-builder/commit/934959df97577595ce8c5a15d66db2fbbe902f3a adds gnat-prefix.

Please confirm.  Thanks.

Edit: I'm not sure whether it's MAKEFLAGS, MAKEOVERRIDES or something else that is leaking make command line definitions.

**Comment by Blady-Com** [comment]
Hello Steve, it's ok for me with your last commit and adding gnat-prefix on the command line though I'm not sure that unset is then really necessary.
Thanks Pascal.

**Comment by steve-cs** [comment]
You're correct that the "unset prefix" doesn't appear to be strictly necessary any more.  However, it does provide an extra bit of protection if prefix ends up in the environment again.  For instance I don't really understand why your initial commenting out of the prefix definition in Makefile worked while I'm still defining and using prefix internally.  I'm tempted to leave it in until I clean up and change all "prefix" to "gnat-prefix".

Thanks again for your help.
