### ISSUE TITLE
ImportError: No module named gi.

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#3]
Hello Steve,
I've achieved GPS build from:
commit 8280c3548cdf43e9dcba52802d22e8b2723004ea (HEAD -> master, origin/master, origin/HEAD)
Author: Anthony Leonardo Gracio <leonardo@adacore.com>
Date:   Sat Mar 16 19:26:21 2019 +0100

When I launch GPS I've got this Python Error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gi
Unexpected fatal error, GPS is in an inconsistent state

Do you have an installed "gi"?
Where does it come from?

Thanks, Pascal.

**Comment by steve-cs** [comment]
Yes, it's part of gps-depends.  apt-get loads it as part of python-gi-dev into /usr with the other dependencies and then /usr/python2.7/* is copied to $(prefix)/python2.7 where $(prefix)/gps finds it at run time.

https://packages.ubuntu.com/bionic/python-gi

Edit: In case it's not obvious, gi is PyGObject:

https://pygobject.readthedocs.io/en/latest/getting_started.html#macosx-getting-started

**Comment by GuillermoHazebrouck** [comment]
Got this same error (but GPS is not crashing). I don't understand very well how all this work, but in my eyes all this process of moving files and dependencies looks complex and extremely brittle...

**Comment by steve-cs** [comment]
In practice this is not as complex or brittle as it seems at first glance.  The alternatives are to either install in /usr or to compile/build/install all the dependencies into $(prefix).  Both of these have their own sets of issues and are significantly more work.  As gnat-builder is largely a proof of concept, the simplest hack was/is to use the OS to install dependency binaries (typically in /usr) and then copy the minimum necessary into $(prefix) so that gps and spark2014 run.
